name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npm run build
      - run: curl -X POST -d {} https://api.netlify.com/build_hooks/62347f61a2844131a0f8ef15
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens


